# Generated by Django 4.2 on 2025-08-15 12:00

from django.db import migrations, models
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events2Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default=events.models.random_event_id, max_length=30, db_index=True)),
                ('queue', models.IntegerField(default=events.models.last_queue)),
                ('is_ready', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=500)),
                ('post', models.TextField(default=events.models.default_post_text, blank=True)),
                ('prepared_text', models.TextField(blank=True, default='', null=True)),
                ('full_text', models.TextField(blank=True, default='', null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('url', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('ReadyToPost', 'Ready To Post'), ('Posted', 'Posted'), ('ForFuture', 'For Future'), ('Spam', 'Spam'), ('Scrape', 'Scrape It')], default='ReadyToPost', max_length=15, db_index=True)),
                ('price', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('explored_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date and time')),
                ('post_date', models.DateTimeField(blank=True, null=True, verbose_name='datetime for posting')),
                ('from_date', models.DateTimeField(default=events.models.default_event_date, verbose_name='event from_date')),
                ('to_date', models.DateTimeField(default=events.models.default_event_date, verbose_name='event to_date')),
                ('post_url', models.CharField(blank=True, max_length=500, null=True)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.place')),
            ],
        ),
        migrations.CreateModel(
            name='EventsNotApprovedNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=30)),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('title', models.CharField(max_length=500)),
                ('post', models.TextField(blank=True, default='')),
                ('full_text', models.TextField(blank=True, default='', null=True, verbose_name='Текст мероприятия')),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('price', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=500, null=True, verbose_name='Категория (тип мероприятия)')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('explored_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date and time')),
                ('from_date', models.DateTimeField(default=events.models.default_event_date, verbose_name='event date_from')),
                ('to_date', models.DateTimeField(blank=True, default=events.models.default_event_date, verbose_name='event to_date')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.place')),
            ],
        ),
        migrations.CreateModel(
            name='EventsNotApprovedProposed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default=events.models.random_event_id, max_length=30)),
                ('approved', models.BooleanField(default=False)),
                ('title', models.CharField(default='', max_length=500, verbose_name='Заголовок')),
                ('post', models.TextField(blank=True, default='')),
                ('full_text', models.TextField(blank=True, default='', null=True, verbose_name='Текст мероприятия')),
                ('image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на изображение')),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка на мероприятие')),
                ('price', models.CharField(default='1000₽', max_length=500, verbose_name='Цена')),
                ('category', models.CharField(blank=True, max_length=500, null=True, verbose_name='Категория (тип мероприятия)')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('explored_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date and time')),
                ('from_date', models.DateTimeField(blank=True, default=events.models.default_event_date, null=True, verbose_name='Дата и время начала мероприятия')),
                ('to_date', models.DateTimeField(blank=True, default=events.models.default_event_date, null=True, verbose_name='Дата и время окончания мероприятия')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.place')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=500)),
                ('parameter_name', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=500)),
                ('commentary', models.CharField(max_length=500, null=True)),
                ('full_value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_weekday', models.IntegerField(default=4)),
                ('end_weekday', models.IntegerField(default=6)),
                ('posting_time_hours', models.IntegerField(default=13)),
                ('posting_time_minutes', models.IntegerField(default=20)),
                ('posting_time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default=events.models.random_event_id, max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('post', models.TextField(blank=True, default='')),
                ('full_text', models.TextField(blank=True, default='', null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('post_url', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('pub_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date and time')),
                ('from_date', models.DateTimeField(default=events.models.default_event_date, verbose_name='event from_date')),
                ('to_date', models.DateTimeField(default=events.models.default_event_date, verbose_name='event to_date')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.place')),
            ],
        ),
    ]
