# Generated by Django 4.2 on 2025-09-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="events2post",
            name="price_int",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventsnotapprovednew",
            name="price_int",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventsnotapprovedproposed",
            name="price_int",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
