# Generated by Django 4.2 on 2025-10-31 03:41

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0002_events2post_price_int_eventsnotapprovednew_price_int_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="events2post",
            name="ticket_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="eventsnotapprovednew",
            name="ticket_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="eventsnotapprovedproposed",
            name="ticket_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="events2post",
            name="source",
            field=models.CharField(
                choices=[
                    ("TIMEPAD", "Timepad"),
                    ("RADARIO", "Radario"),
                    ("TC", "Ticketscloud"),
                    ("QT", "QTickets"),
                    ("CLTR", "Culture"),
                    ("MTS", "MTS"),
                    ("VK", "VK"),
                    ("AI", "AI"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventsnotapprovednew",
            name="source",
            field=models.CharField(
                choices=[
                    ("TIMEPAD", "Timepad"),
                    ("RADARIO", "Radario"),
                    ("TC", "Ticketscloud"),
                    ("QT", "QTickets"),
                    ("CLTR", "Culture"),
                    ("MTS", "MTS"),
                    ("VK", "VK"),
                    ("AI", "AI"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventsnotapprovedproposed",
            name="source",
            field=models.CharField(
                choices=[
                    ("TIMEPAD", "Timepad"),
                    ("RADARIO", "Radario"),
                    ("TC", "Ticketscloud"),
                    ("QT", "QTickets"),
                    ("CLTR", "Culture"),
                    ("MTS", "MTS"),
                    ("VK", "VK"),
                    ("AI", "AI"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
