# Generated by Django 4.2 on 2026-02-10 09:58

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_events2post_ticket_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsnotapprovednew",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("extracted", "Extracted"),
                    ("not_event", "Not Event"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("spam", "Spam"),
                    ("duplicate", "Duplicate"),
                ],
                db_index=True,
                default="new",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventsnotapprovedproposed",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("extracted", "Extracted"),
                    ("not_event", "Not Event"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("spam", "Spam"),
                    ("duplicate", "Duplicate"),
                ],
                db_index=True,
                default="new",
                max_length=30,
                null=True,
            ),
        ),
    ]
