# Generated by Django 4.2 on 2026-03-03 08:41

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_eventsnotapprovednew_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="events2post",
            name="score",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="total event score"
            ),
        ),
        migrations.AddField(
            model_name="events2post",
            name="score_breakdown",
            field=models.JSONField(
                blank=True, null=True, verbose_name="event score by categories"
            ),
        ),
        migrations.AddField(
            model_name="eventsnotapprovednew",
            name="score",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="total event score"
            ),
        ),
        migrations.AddField(
            model_name="eventsnotapprovednew",
            name="score_breakdown",
            field=models.JSONField(
                blank=True, null=True, verbose_name="event score by categories"
            ),
        ),
        migrations.AddField(
            model_name="eventsnotapprovedproposed",
            name="score",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="total event score"
            ),
        ),
        migrations.AddField(
            model_name="eventsnotapprovedproposed",
            name="score_breakdown",
            field=models.JSONField(
                blank=True, null=True, verbose_name="event score by categories"
            ),
        ),
        migrations.AlterField(
            model_name="eventsnotapprovednew",
            name="from_date",
            field=models.DateTimeField(
                blank=True,
                default=events.models.default_event_date,
                null=True,
                verbose_name="event date_from",
            ),
        ),
    ]
