# Generated by Django 3.1.7 on 2024-11-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('events', '0025_auto_20240805_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='full_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
