# Generated by Django 3.1.7 on 2025-02-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20241107_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='events2post',
            name='prepared_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
