# Generated by Django 4.2 on 2025-06-12 08:14

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название подборки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("ready", "Готов к обработке"),
                            ("processing", "В обработке"),
                            ("completed", "Обработан"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "generation_settings",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=1,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Подборка мероприятий",
                "verbose_name_plural": "Подборки мероприятий",
            },
        ),
        migrations.CreateModel(
            name="GeneratedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Заголовок поста"),
                ),
                ("content", models.TextField(verbose_name="Содержание поста")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("scheduled", "Запланирован"),
                            ("published", "Опубликован"),
                            ("cancelled", "Отменен"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, null=True)),
                ("media_files", models.JSONField(blank=True, default=list, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "event_selection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_generator.eventselection",
                        verbose_name="Подборка мероприятий",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        default=1,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сгенерированный пост",
                "verbose_name_plural": "Сгенерированные посты",
            },
        ),
        migrations.CreateModel(
            name="PostTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название шаблона"),
                ),
                ("template_text", models.TextField(verbose_name="Текст шаблона")),
                (
                    "variables",
                    models.JSONField(
                        default=list, help_text="Список переменных в шаблоне"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Шаблон поста",
                "verbose_name_plural": "Шаблоны постов",
            },
        ),
        migrations.CreateModel(
            name="PostingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(verbose_name="Время публикации"),
                ),
                (
                    "platform",
                    models.CharField(
                        help_text="Telegram, VK, etc.",
                        max_length=50,
                        verbose_name="Платформа",
                    ),
                ),
                ("platform_settings", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "is_posted",
                    models.BooleanField(default=False, verbose_name="Опубликован"),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время публикации"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Сообщение об ошибке"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="Количество попыток"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "generated_post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_generator.generatedpost",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание постинга",
                "verbose_name_plural": "Расписание постинга",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.AddField(
            model_name="generatedpost",
            name="post_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content_generator.posttemplate",
                verbose_name="Шаблон поста",
            ),
        ),
        migrations.CreateModel(
            name="FilterSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название набора фильтров"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[
                            ("standard", "Стандартный"),
                            ("custom", "Пользовательский"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "filter_params",
                    models.JSONField(
                        default=dict, help_text="Параметры фильтрации в JSON формате"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=1,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Набор фильтров",
                "verbose_name_plural": "Наборы фильтров",
            },
        ),
        migrations.AddField(
            model_name="eventselection",
            name="filter_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="content_generator.filterset",
                verbose_name="Набор фильтров",
            ),
        ),
        migrations.AddField(
            model_name="eventselection",
            name="selected_events",
            field=models.ManyToManyField(
                blank=True, to="events.events2post", verbose_name="Выбранные мероприятия"
            ),
        ),
    ]
