# Generated by Django 4.2 on 2025-09-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedpost",
            name="image",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Ссылка на изображение",
            ),
        ),
        migrations.AddField(
            model_name="generatedpost",
            name="image_upload",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
        migrations.AddField(
            model_name="postingschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("ReadyToPost", "Ready To Post"),
                    ("Posted", "Posted"),
                    ("ForFuture", "For Future"),
                    ("Spam", "Spam"),
                ],
                db_index=True,
                default="ReadyToPost",
                max_length=15,
            ),
        ),
    ]
