# Generated by Django 4.2 on 2025-11-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_id_alter_subcategory_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_local",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
