# Generated by Django 3.1.7 on 2025-01-08 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_testeventplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='place_images/'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='PlaceSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('std', 'Standard'), ('hol', 'Holiday'), ('spl', 'Special')], max_length=10)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='place.place')),
            ],
        ),
        migrations.AddConstraint(
            model_name='placeschedule',
            constraint=models.UniqueConstraint(fields=('place', 'schedule_type', 'weekday', 'date'), name='unique_schedule'),
        ),
        migrations.AddConstraint(
            model_name='placeschedule',
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(('schedule_type', 'std'), ('date__isnull', True), ('weekday__isnull', False)),
                               models.Q(('schedule_type', 'spl'), ('date__isnull', False), ('weekday__isnull', True)),
                               models.Q(('schedule_type', 'hol'), ('weekday__isnull', True)), _connector='OR'),
                name='valid_schedule_type_constraint'),
        ),
    ]
