# Generated by Django 3.1.7 on 2025-02-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20250108_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeschedule',
            name='close_time',
            field=models.TimeField(blank=True, default='18:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='placeschedule',
            name='open_time',
            field=models.TimeField(blank=True, default='10:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='placeschedule',
            name='schedule_type',
            field=models.CharField(choices=[('std', 'Standard'), ('hol', 'Holiday'), ('spl', 'Special')], default='std', max_length=10),
        ),
        migrations.AlterField(
            model_name='placeschedule',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '-'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
    ]
