# Generated by Django 4.2 on 2026-05-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0005_alter_place_id_alter_placekeyword_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Категория, которая присваивается всем мероприятиям этой площадки",
                max_length=500,
            ),
        ),
    ]
