# Generated by Django 4.2 on 2026-07-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0006_place_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "place_city",
                    models.CharField(
                        blank=True,
                        default="SPb",
                        help_text="Город района: Петроградка (СПб) ≠ район в Казани.",
                        max_length=500,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Вышестоящий район/округ/область. Пусто = верхний уровень.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="place.district",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="district_raw",
            field=models.CharField(
                blank=True,
                help_text="Район как пришёл из источника. Вспомогательный сигнал для привязки к district.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="main_place",
            field=models.ForeignKey(
                blank=True,
                help_text="Родительский комплекс/хаб. Пусто = самостоятельная площадка (верхний уровень).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="place.place",
            ),
        ),
        migrations.CreateModel(
            name="DistrictKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district_keyword", models.CharField(max_length=200)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="place.district",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="district",
            field=models.ForeignKey(
                blank=True,
                help_text="Район (источник истины). Резолвится из district_raw через DistrictKeyword.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="places",
                to="place.district",
            ),
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.UniqueConstraint(
                fields=("name", "place_city"), name="unique_district_name_city"
            ),
        ),
    ]
